### ISSUE TITLE
Deployments failing on step AnsiblePhase6Part1_SAS_INSTALL

### ISSUE THREAD

**Issue by MiskyCAN** [sassoftware/quickstart-sas-viya-azure#84] opened 2020-06-02 21:09 UTC
Receiving an error in this step:
TASK [prepare_deployment/deployment_mirror : install azcopy prerequisites] *****
failed: [services] (item=[u'libunwind', u'icu', u'rsync']) => {
    "changed": false,
    "item": [
        "libunwind",
        "icu",
        "rsync"
    ],
    "rc": 126,
    "results": [
        "All packages providing libunwind are up to date",
        "No package matching 'icu' found available, installed or updated"
    ]
}

I checked the rhel repo on the Ansible controller and there is no longer any package available called icu:
[vmuser@Ansible install]$ yum list ic*
Loaded plugins: langpacks, product-id, search-disabled-repos
Repo rhui-rhel-7-server-dotnet-rhui-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-7-server-dotnet-rhui-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
Repo rhui-rhel-7-server-rhui-extras-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-7-server-rhui-extras-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
Repo rhui-rhel-7-server-rhui-rh-common-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-7-server-rhui-rh-common-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
Repo rhui-rhel-7-server-rhui-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-7-server-rhui-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
Repo rhui-rhel-7-server-rhui-supplementary-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-7-server-rhui-supplementary-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
Repo rhui-rhel-server-rhui-rhscl-7-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/product/content.crt
Repo rhui-rhel-server-rhui-rhscl-7-rpms forced skip_if_unavailable=True due to: /etc/pki/rhui/key.pem
rhui-microsoft-azure-rhel7                                                                                                                                         10/10
rhui-rhel-7-server-dotnet-rhui-rpms                                                                                                                              448/448
rhui-rhel-7-server-rhui-extras-rpms                                                                                                                            1285/1285
rhui-rhel-7-server-rhui-rh-common-rpms                                                                                                                           242/242
rhui-rhel-7-server-rhui-rpms                                                                                                                                 29096/29096
rhui-rhel-7-server-rhui-supplementary-rpms                                                                                                                       376/376
rhui-rhel-server-rhui-rhscl-7-rpms                                                                                                                           12714/12714
Available Packages
icedax.x86_64                                                           1.1.11-25.el7                                                        rhui-rhel-7-server-rhui-rpms
icedtea-web.x86_64                                                      1.7.1-2.el7_6                                                        rhui-rhel-7-server-rhui-rpms
icoutils.x86_64                                                         0.31.3-1.el7_3                                                       rhui-rhel-7-server-rhui-rpms

**Comment by MiskyCAN** [comment] 2020-06-03 22:22
Did some more digging while waiting for someone to get this assigned...

On Centos, icu is available in the updates repo:
Name        : icu
Version     : 50.2
Release     : 4.el7_7
Architecture: x86_64
Size        : 448152
Packager    : CentOS BuildSystem <http://bugs.centos.org>
Group       : Development/Tools
URL         : http://www.icu-project.org/
Repository  : **updates**
Summary     : International Components for Unicode
Source      : **icu-50.2-4.el7_7.src.rpm**

On RedHat, there doesn't seem to be any reference for icu in any of the base repos, but a libicu is available in the rhui-rhel-7-server-rhui-rpms repo based on the same source.
Name        : libicu
Version     : 50.2
Release     : 4.el7_7
Architecture: i686
Size        : 25183713
Packager    : Red Hat, Inc. <http://bugzilla.redhat.com/bugzilla>
Group       : System Environment/Libraries
URL         : http://www.icu-project.org/
Repository  : **rhui-rhel-7-server-rhui-rpms**
Summary     : International Components for Unicode - libraries
Source      : **icu-50.2-4.el7_7.src.rpm**

**Comment by chlync** [comment] 2020-06-05 20:14
Thanks for raising the issue.

It looks like ICU was renamed to libicu. No idea why. This [pull request](https://github.com/sassoftware/quickstart-sas-viya-azure/pull/85) should include the fix and we are working internally to regression test this and then push up to Azure.

**Comment by satelitexp** [comment] 2020-07-09 22:05
Did you update the deployment to azure yet?  I am still having issues with the AnsiblePhase6Part1RunViyaInstall

**Comment by patbrown56** [comment] 2020-11-03 23:26
An update for this issue has been pushed to Azure, and I have launched a deployment to verify that it no longer occurs. Please let us know if you continue to see the problem.

**Comment by patbrown56** [comment] 2020-12-10 19:16
This issue has been resolved. Closing.

**Closed by patbrown56** 2020-12-10 19:16 UTC
